
void TIM2_Setup_ENC (void);

enum {
    VOLUME, MENU, OPMODE, DELAY,
    DEBUG, QEIMODE, IMPSSTEP, ENABLEIR,
    THEME, SSAVER, IRVUP, IRVDOWN, IRMUTE, IRCHSW, IRPOWER, INPUTCH};

//timer labels
enum {T_BUTTON, T_EDIT_BLINK, T_EDIT_OFF, T_WAKEUP, T_UN_4, T_SSAVER, T_FPS, T_RY};
